<a href="https://colab.research.google.com/github/CodeAbsolute/machine_learning-data_science/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NUMPY TUTORIAL:**

In [ ]:
import numpy as np

np1 = np.array([[1, 2],[3,4]])
np2 = np.array([[4, 5],[6,7] ])

# multiplying two arrays
mnp1 = np1@np2 # @ works like matrix multiplication
mnp2 = np1*np2 # * multiplies same index elements
mnp3 = np.dot(np1,np2)
mnp4 = np.multiply(np1,np2)


print(f"mnp1:  {mnp1}")
print(f"mnp2:  {mnp2}")
print(f"mnp3:  {mnp3}")
print(f"mnp4:  {mnp4}")


In [ ]:
# get the sum of all elements in the array
sum = np.sum(np1)
print("sum: ", sum)

# Adding 2 arrays
add2arr = np.add(np1,np2)
print("add2arr: ", add2arr)

sum1 = np1 + np2
print("sum1: ", sum1)


In [ ]:
# Subtracting 2 arrays
diff = np1 - np2
print("diff: ", diff)
 
sub2arr = np.subtract(np1,np2)
print("sub2arr: ", sub2arr)


In [ ]:
#divide 2 arrays
print("np1/np2: ", np1/np2)

div = np.divide(np1,np2)
print("div: ", div)

# integer division
div = np.floor_divide(np1,np2)
print(div)

In [14]:
# random normal distribution
normal_distribution = np.random.standard_normal((3,3))
print("normal_distribution: ",normal_distribution)

#random uniform distribution
uniform_distribution = np.random.uniform(1,1000,[4,3])
print("uniform_distribution: ",uniform_distribution)

print(np.math.sqrt(15))

normal_distribution:  [[-0.24749421  1.9118735   0.61070036]
 [ 0.30218871  0.14450863  0.37981832]
 [-0.77433271 -0.03769768 -1.02157986]]
uniform_distribution:  [[103.73386494 703.1399064   95.86466753]
 [124.38898874 158.71478574 509.32556997]
 [873.19644652 526.07494396 409.34854055]
 [845.05417981 375.43299554 133.51258989]]
3.872983346207417


In [22]:
#generate random float no.
print(np.random.rand())

# generate random integer no.
print(np.random.randint(1,10000,(2,4)))

0.1537162632003587
[[2506  482 6537 8780]
 [ 556 7885 8519 9960]]


In [24]:
# Zeros & Ones
print("Zeros: ", np.zeros((5,5)))
print("Ones: ", np.ones((5,5)))

Zeros:  [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Ones:  [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# Filter Arrays
filter = np.logical_and(np1>1,np1<5) # returning a bool array with the indicies matching are true else false
print("np1: ",np1)
print("filter: ",filter)
filtered_arr = np1[filter]
print("filtered_arr: ",filtered_arr)

In [35]:
from numpy.lib.function_base import median
arr = np.array([1,2,3,4,7,9,10])
# Average / Mean
avg = np.mean(arr)
print("Mean of arr: ",avg)

# Median of arr
medi = np.median(arr)
print("Median of arr: ", medi)

# variance of arr
vari = np.var(arr)
print("Variance of arr: ", vari)

# standard deviation of arr
sd = np.std(arr)
print("Standard Deviation of arr: ", sd)

Mean of arr:  5.142857142857143
Median of arr:  4.0
Variance of arr:  10.693877551020408
Standard Deviation of arr:  3.270149469217028


In [40]:
np_arr = np.array([[1,2,3],[4,5,6]])
print("np_arr: ", np_arr)

# variance
vari = np.var(np_arr,axis=1) # axis = 1 calculates the variance for the rows 
print("vari with axis = 1: ", vari)

vari = np.var(np_arr,axis=0) # axis = 0 calculates the variance for the columns
print("vari with axis = 0: ", vari)

np_arr:  [[1 2 3]
 [4 5 6]]
vari with axis = 1:  [0.66666667 0.66666667]
vari with axis = 0:  [2.25 2.25 2.25]
